### ISSUE TITLE
Highlight line in combination with emojis

### ISSUE THREAD

**Issue by christophrumpel** [spatie/commonmark-highlighter#13]
If you try to highlight a specific line in combination with an emoji, the emoji will not be shown anymore:

```php

    ```php{2}
    // ✅ ...
    $isUserPending = $user->isStatus('pending');
    ```
```

<img width="504" alt="Screen Shot 2020-08-26 at 20 14 51" src="https://user-images.githubusercontent.com/1394539/91341059-40d76980-e7d9-11ea-9f53-101d019d2340.png">

Without the `{2}` the emoji is shown correctly:

```php

    ```php
    // ✅ ...
    $isUserPending = $user->isStatus('pending');
    ```
```

![image](https://user-images.githubusercontent.com/1394539/91341124-55b3fd00-e7d9-11ea-8668-c2d96615d51e.png)

Have you an idea what this is about @allejo?


PS: Here some info about how I set up the converter:

```php
        $environment = Environment::createCommonMarkEnvironment();
        $languages = ['html', 'php', 'js', 'shell', 'shell'];

        $environment->addBlockRenderer(FencedCode::class, new FencedCodeRenderer($languages));
        $environment->addBlockRenderer(IndentedCode::class, new IndentedCodeRenderer($languages));

        $commonMarkConverter = new CommonMarkConverter([], $environment);

        return $commonMarkConverter->convertToHtml($codeExample);
```

**Comment by allejo** [comment]
Thanks for bringing this up to me, it appears to me like this is an upstream issue. I've fixed the issue over at https://github.com/scrivo/highlight.php/pull/76.

After a bit more testing, I'll merge and a PR can be made against this repo for the new patch release.

**Comment by christophrumpel** [comment]
Thanks for taking care of it :-)

A bit unrelated, but do you think it would be possible to highlight just some fragments too instead of only lines?
Maybe by defining these parts in the code example ad it gets converted to HTML instead of showing the code?

```php

    ```php
    $isUserPending = <span class="highlight">$user->isStatus('pending')</span>;
    ```
```

**Comment by sebastiandedeyne** [comment]
I think that's also more up to highlight.php to support, this is just a bridge between highlight and CommonMark.

**Comment by allejo** [comment]
> A bit unrelated, but do you think it would be possible to highlight just some fragments too instead of only lines?
> 
> Maybe by defining these parts in the code example ad it gets converted to HTML instead of showing the code?
> 
> 
> 
> ```php
> 
> 
> 
>     ```php
> 
>     $isUserPending = <span class="highlight">$user->isStatus('pending')</span>;
> 
>     ```
> 
> ```

Unfortunately not at the highlight.php level, see the discussion here https://github.com/scrivo/highlight.php/issues/62

Highlighting like this would need to happen at the markdown extension level.

**Comment by christophrumpel** [comment]
Thanks @allejo! Found a solution. @sebastiandedeyne showed me how @brendt managed something like that here https://github.com/brendt/stitcher.io/blob/master/src/Plugin/Markdown/HighlightCodeBlockRenderer.php 👍

**Comment by christophrumpel** [comment]
@sebastiandedeyne so will the open PR be closed? Do I need to bring this bug to the other package?
