### ISSUE TITLE
Add .hljs class to all blocks

### ISSUE THREAD

**Issue by abdul-alhasany** [spatie/commonmark-highlighter#24]
Hi
Is it possible to add `.hljs` class even to blocks with unsupported languages. Currently, unsupported languages (like blade, vue ..etc) display without a background when applying a theme. This will confuse the reader as they appear just like a regular text.

This is without apply the class:
![image](https://github.com/spatie/commonmark-highlighter/assets/1753883/5c7cc224-114d-4cf5-9afe-526b59d23d38)

This is with the class applied:
![image](https://github.com/spatie/commonmark-highlighter/assets/1753883/261bebe7-6d7d-4eec-94e1-3e5b5cfb408d)

**Comment by sebastiandedeyne** [comment]
I'd accept a PR that adds this. Although it'd be a breaking change, so might tag a major if we merge.

**Comment by abdul-alhasany** [comment]
After many tries I was able to figure out the issue.
I did not add 
`use League\CommonMark\Extension\CommonMark\Node\Block\IndentedCode;`
to the top of the file. This was the code that did not get rendered.

Once I added it, everything worked fine.
