### ISSUE TITLE
Updating to work with Commonmark 1.0.0

### ISSUE THREAD

**Issue by jonnybarnes** [spatie/commonmark-highlighter#7]
Commonmark v1.0.0 changes the `League\CommonMark\Block\Renderer\FencedCodeRenderer` to be a `final` class, so it can’t be extended anymore.

**Comment by freekmurze** [comment]
If asked the maintainers to make those non-final: https://github.com/thephpleague/commonmark/issues/379

**Comment by rubenvanassche** [comment]
Fixed with release 2.0.0

**Comment by sebastiandedeyne** [comment]
❤️
