### ISSUE TITLE
Add line highlighting support

### ISSUE THREAD

**Issue by allejo** [spatie/commonmark-highlighter#9]
The [CommonMark spec allows for any arbitrary content to exist in the info string of a code block](https://spec.commonmark.org/0.29/#example-113). Would you be open to adding support for highlighting specific lines of code within said code block?

~~~markdown
```html{2}
<div>
  <p>I wish I wish I was a fish</p>
</div>
```
~~~

**Proposed Syntax**

- `html{4}` - highlight the 4th line of the code block
- `html{4-5}` - highlight the 4th through 5th lines of code
- `html{1,4-5}` - highlight the 1st and 4th through 5th line of code separately

**Comment by sebastiandedeyne** [comment]
I'd very much be interested in this!

I don't really have time to implement this myself atm, but I'll gladly accept a PR.

**Comment by allejo** [comment]
Sure thing! I can work on a PR for this, just wanted to make sure it'd be received favorably before I worked on it.
